authors:
  Frederic Loui:
    name: Frederic Loui
    slug: frederic-loui
    description: Frederic Loui is the creator of nmaas
    avatar: 'https://avatars.githubusercontent.com/u/9639687?v=4'
    url: 'https://github.com/frederic-loui'
  korvoj:
    name: korvoj
    slug: korvoj
    description: ' '
    avatar: 'https://avatars.githubusercontent.com/u/4062681?v=4'
    url: 'https://github.com/korvoj'
  pkazimierowski:
    name: Patryk Kazimierowski
    slug: pkazimierowski
    description: ' '
    url: 'https://gitlab.software.geant.org/pkazimierowski'
    avatar: 'https://gitlab.software.geant.org/uploads/-/system/user/avatar/582/avatar.png'